// Generated by token-saver. Re-run install.py to update this path.
import { spawn } from "node:child_process"

const BRIDGE = "/home/joseph/.token-saver/kilo/compress.py"
const GRAPHIFY_METRICS = "/home/joseph/.token-saver/src/graphify_metrics.py"
const PYTHON = process.platform === "win32" ? "python" : "python3"
const BASH_TOOLS = new Set([
  "bash", "shell", "execute_command", "executeCommand",
  "runCommand", "run_command", "sh",
])

// Tools that produce compressible text output.  Each maps to a synthetic
// command string so the Python engine routes to the right processor.
// Tools not listed here (write, edit, todowrite, question, etc.) produce
// only short confirmations or user input — not worth compressing.
const TOOL_COMMAND = {
  read:            (a) => `cat ${a.filePath ?? a.path ?? ""}`,
  grep:            (a) => `grep ${a.pattern ?? ""} ${a.path ?? a.include ?? ""}`,
  glob:            (a) => `find ${a.path ?? "."} -name ${a.pattern ?? ""}`,
  task:            (a) => `task ${a.description ?? a.subagent_type ?? ""}`,
  webfetch:        (a) => `curl ${a.url ?? ""}`,
  websearch:       (a) => `websearch ${a.query ?? ""}`,
  codebase_search: (a) => `codebase_search ${a.query ?? ""}`,
  lsp:             (a) => `lsp ${a.operation ?? a.command ?? ""}`,
}

function compress(command, output, sessionID, tool) {
  return new Promise((resolve) => {
    const child = spawn(PYTHON, [BRIDGE], { stdio: ["pipe", "pipe", "ignore"] })
    let stdout = ""
    child.stdout.setEncoding("utf8")
    child.stdout.on("data", (chunk) => { stdout += chunk })
    child.on("error", () => resolve(null))
    const timer = setTimeout(() => { child.kill(); resolve(null) }, 30000)
    child.on("close", (code) => {
      clearTimeout(timer)
      if (code !== 0 || !stdout) return resolve(null)
      try { resolve(JSON.parse(stdout)) } catch { resolve(null) }
    })
    child.stdin.end(JSON.stringify({ command, output, session_id: sessionID, tool: tool || "" }))
  })
}

function compressGraphify(project, question, output, sessionID) {
  return new Promise((resolve) => {
    const child = spawn(
      PYTHON, [GRAPHIFY_METRICS],
      { stdio: ["pipe", "ignore", "ignore"] },
    )
    child.on("error", () => resolve())
    const timer = setTimeout(() => { child.kill(); resolve() }, 5000)
    child.on("close", () => { clearTimeout(timer); resolve() })
    child.stdin.end(
      JSON.stringify({ project, question, output, session_id: sessionID }),
    )
  })
}

const GRAPHIFY_QUERY_RE = /^graphify\s+query\s+(["'])([\s\S]*?)\1(?:\s|$)/

const TokenSaver = async () => {
  return {
    "tool.execute.before": async (input, output) => {
      if (!BASH_TOOLS.has(String(input.tool || "").toLowerCase())) return
      const command = output.args?.command
      const match = typeof command === "string"
        ? command.match(GRAPHIFY_QUERY_RE)
        : null
      if (match) output.args.__tokenSaverGraphifyQuestion = match[2]
    },
    "tool.execute.after": async (input, output) => {
      const tool = String(input.tool || "")
      const isBash = BASH_TOOLS.has(tool.toLowerCase())
      // Build the command string for processor routing
      let command
      if (isBash) {
        command = input.args?.command
      } else {
        const builder = TOOL_COMMAND[tool]
        command = typeof builder === "function" ? builder(input.args || {}) : null
      }
      if (typeof command !== "string" || typeof output.output !== "string") return
      // Graphify metrics only for bash commands
      if (isBash) {
        const graphifyMatch = command.match(GRAPHIFY_QUERY_RE)
        const question = input.args?.__tokenSaverGraphifyQuestion || graphifyMatch?.[2]
        if (typeof question === "string") {
          await compressGraphify(
            input.args?.workdir || process.cwd(),
            question, output.output, input.sessionID,
          )
        }
      }
      const result = await compress(command, output.output, input.sessionID, tool)
      if (result?.compressed === true && typeof result.output === "string") {
        output.output = result.output
        output.metadata = { ...(output.metadata || {}), tokenSaver: result.stats }
      }
    },
  }
}

export default { id: "token-saver", server: TokenSaver }
