"""Kilo Code installer for Token-Saver.

Kilo loads JavaScript/TypeScript plugins from ``~/.config/kilo/plugins``.
The plugin installed here uses Kilo's ``tool.execute.after`` hook to compress
the output of completed Bash tool calls without executing the command twice.
"""

import json
import os

from .common import IS_WINDOWS, home, install_files, token_saver_data_dir

_PLUGIN_NAME = "token-saver.js"


def _config_dir():
    """Return Kilo's canonical global configuration directory."""
    override = os.environ.get("KILO_CONFIG_DIR")
    if override:
        return os.path.abspath(os.path.expanduser(override))
    if IS_WINDOWS:
        appdata = os.environ.get("APPDATA", os.path.join(home(), "AppData", "Roaming"))
        return os.path.join(appdata, "kilo")
    return os.path.join(home(), ".config", "kilo")


def _plugin_path():
    return os.path.join(_config_dir(), "plugins", _PLUGIN_NAME)


def _skill_dir():
    return os.path.join(_config_dir(), "skills", "token-saver-config")


def _graphify_skill_dir():
    return os.path.join(_config_dir(), "skills", "token-saver-graphify")


def _command_path():
    return os.path.join(_config_dir(), "commands", "token-saver-stats.md")


def _render_plugin() -> str:
    """Render the local Kilo plugin with an absolute Python bridge path."""
    bridge = os.path.join(token_saver_data_dir(), "kilo", "compress.py")
    return f'''// Generated by token-saver. Re-run install.py to update this path.
import {{ spawn }} from "node:child_process"

const BRIDGE = {json.dumps(bridge)}
const PYTHON = process.platform === "win32" ? "python" : "python3"
const BASH_TOOLS = new Set(["bash", "shell"])

function compress(command, output, sessionID) {{
  return new Promise((resolve) => {{
    const child = spawn(PYTHON, [BRIDGE], {{ stdio: ["pipe", "pipe", "ignore"] }})
    let stdout = ""
    child.stdout.setEncoding("utf8")
    child.stdout.on("data", (chunk) => {{ stdout += chunk }})
    child.on("error", () => resolve(null))
    const timer = setTimeout(() => {{ child.kill(); resolve(null) }}, 30000)
    child.on("close", (code) => {{
      clearTimeout(timer)
      if (code !== 0 || !stdout) return resolve(null)
      try {{ resolve(JSON.parse(stdout)) }} catch {{ resolve(null) }}
    }})
    child.stdin.end(JSON.stringify({{ command, output, session_id: sessionID }}))
  }})
}}

export const TokenSaver = async () => ({{
  "tool.execute.after": async (input, output) => {{
    if (!BASH_TOOLS.has(String(input.tool || "").toLowerCase())) return
    const command = input.args?.command
    if (typeof command !== "string" || typeof output.output !== "string") return
    const result = await compress(command, output.output, input.sessionID)
    if (result?.compressed === true && typeof result.output === "string") {{
      output.output = result.output
      output.metadata = {{ ...(output.metadata || {{}}), tokenSaver: result.stats }}
    }}
  }},
}})
'''


def install(use_symlink=False):
    """Install the Kilo plugin, Python bridge, skill, and stats command."""
    config_dir = _config_dir()
    plugin_path = _plugin_path()
    print(f"\n--- Kilo Code ({config_dir}) ---")

    os.makedirs(os.path.dirname(plugin_path), exist_ok=True)
    if os.path.exists(plugin_path) or os.path.islink(plugin_path):
        os.remove(plugin_path)
    with open(plugin_path, "w", encoding="utf-8") as f:
        f.write(_render_plugin())
    print(f"  COPY {_PLUGIN_NAME} -> {plugin_path}")

    # Kilo assets are also kept in the core install. Symlinking these user-facing
    # entries in development mode gives immediate skill/command updates.
    install_files(
        config_dir,
        [
            "skills/token-saver-config/SKILL.md",
            "skills/token-saver-graphify/SKILL.md",
            "commands/token-saver-stats.md",
        ],
        use_symlink,
    )
    print("  Plugin installed. Restart Kilo Code to load it.")


def uninstall():
    """Remove Token-Saver's Kilo plugin, skill, and command."""
    print("\n--- Kilo Code ---")
    paths = (_plugin_path(), _command_path())
    for path in paths:
        if os.path.exists(path) or os.path.islink(path):
            os.remove(path)
            print(f"  REMOVED {path}")

    for skill_dir in (_skill_dir(), _graphify_skill_dir()):
        skill_path = os.path.join(skill_dir, "SKILL.md")
        if os.path.exists(skill_path) or os.path.islink(skill_path):
            os.remove(skill_path)
            print(f"  REMOVED {skill_path}")
        if os.path.isdir(skill_dir) and not os.listdir(skill_dir):
            os.rmdir(skill_dir)
